# Generated by Django 3.2 on 2022-07-25 09:35

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20220627_0833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Atribýut', 'verbose_name_plural': 'Atribýutlar'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Bannerlar'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brend', 'verbose_name_plural': 'Brendlar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriýa', 'verbose_name_plural': 'Kategoriýalar'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Teswir', 'verbose_name_plural': 'Teswirler'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Surat', 'verbose_name_plural': 'Suratlar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Haryt', 'verbose_name_plural': 'Harytlar'},
        ),
        migrations.AlterModelOptions(
            name='sampleimages',
            options={'verbose_name': 'Nusga Surat', 'verbose_name_plural': 'Nusga Suratlar'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Sazlama', 'verbose_name_plural': 'Sazlamalar'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Içki Kategoriýa', 'verbose_name_plural': 'Içki Kategoriýalar'},
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand', verbose_name='Brendy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='En-Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Ru-Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_tm',
            field=models.TextField(blank=True, null=True, verbose_name='Tm-Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ulanyşdamy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Ýöritemi?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_usd',
            field=models.BooleanField(default=False, verbose_name='Dollardamy?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='products/default.jpg', upload_to=product.models.product_image, verbose_name='Suraty'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image_mobile',
            field=models.ImageField(default='products/default.jpg', upload_to=product.models.product_image, verbose_name='Mobil Suraty'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, verbose_name='Bahasy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_product', to='product.subcategory', verbose_name='Içki kategoriýa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='En-Ady'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ru-Ady'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_tm',
            field=models.CharField(max_length=255, verbose_name='TM-Ady'),
        ),
    ]
