# Generated by Django 3.2 on 2022-07-25 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0007_auto_20220725_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Baş sahypadamy?'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='En-giňişleýin'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Ru-giňişleýin'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='description_tm',
            field=models.TextField(blank=True, null=True, verbose_name='Tm-giňişleýin'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute', to='product.product', verbose_name='Haryt'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='En-Ady'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ru-Ady'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='title_tm',
            field=models.CharField(max_length=255, verbose_name='Tm-Ady'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(default='general/default.jpg', upload_to=product.models.general_image, verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_mobile',
            field=models.ImageField(default='general/default.jpg', upload_to=product.models.general_image, verbose_name='Mobil Surat'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiwmy'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='general/default.jpg', upload_to=product.models.general_image, verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='general/default.jpg', upload_to=product.models.general_image, verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_mobile',
            field=models.ImageField(default='general/default.jpg', upload_to=product.models.general_image, verbose_name='Mobil Surat'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='En-Ady'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ru-Ady'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_tm',
            field=models.CharField(max_length=255, verbose_name='Tm-Ady'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktiwmy'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comment', to='product.product', verbose_name='Haryt'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='Ulanyjy'),
        ),
        migrations.AlterField(
            model_name='sampleimages',
            name='image',
            field=models.ImageField(default='general/default.jpg', upload_to=product.models.general_image, verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='sampleimages',
            name='image_mobile',
            field=models.ImageField(default='general/default.jpg', upload_to=product.models.general_image, verbose_name='Mobil Surat'),
        ),
        migrations.AlterField(
            model_name='sampleimages',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiwmy'),
        ),
        migrations.AlterField(
            model_name='sampleimages',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='course',
            field=models.FloatField(default=1, verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_sub', to='product.category', verbose_name='Kategoriýa'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='En-Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Ru-Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description_tm',
            field=models.TextField(blank=True, null=True, verbose_name='Tm-Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='En-Ady'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ru-Ady'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title_tm',
            field=models.CharField(max_length=255, verbose_name='Tm-Ady'),
        ),
    ]
