# Generated by Django 3.2 on 2022-07-29 04:06

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20220727_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Ady')),
                ('mobile', models.CharField(max_length=64, verbose_name='Telefon')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stores/', verbose_name='Surat')),
                ('address', models.TextField(null=True, verbose_name='Adres')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiwmy?')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='general/default.jpg', help_text='Bu suratyň ölçegleri 64x64 bolmaly!', upload_to=product.models.general_image, verbose_name='Surat'),
        ),
    ]
