# Generated by Django 3.2 on 2022-07-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20220729_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Serwis',
                'verbose_name_plural': 'Serwislar',
            },
        ),
        migrations.AlterModelOptions(
            name='stores',
            options={'verbose_name': 'Dükan', 'verbose_name_plural': 'Dükanlar'},
        ),
    ]
