# Generated by Django 3.2 on 2022-08-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='stores/')),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='content_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='content_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='content_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='icon_1',
            field=models.ImageField(blank=True, null=True, upload_to='stores/'),
        ),
        migrations.AddField(
            model_name='services',
            name='icon_2',
            field=models.ImageField(blank=True, null=True, upload_to='stores/'),
        ),
        migrations.AddField(
            model_name='services',
            name='icon_3',
            field=models.ImageField(blank=True, null=True, upload_to='stores/'),
        ),
    ]
