# Generated by Django 3.2 on 2022-08-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_productrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='title',
            new_name='title_tm',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='content_1',
            new_name='content_1_en',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='content_2',
            new_name='content_1_ru',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='content_3',
            new_name='content_1_tm',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='description',
            new_name='description_tm',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='title',
            new_name='title_tm',
        ),
        migrations.RenameField(
            model_name='useragreement',
            old_name='title',
            new_name='title_tm',
        ),
        migrations.AddField(
            model_name='services',
            name='content_2_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='content_2_tm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='content_3_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='content_3_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='content_3_tm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
