# Generated by Django 3.2 on 2022-08-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20220815_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='GifBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Gif Image', max_length=255)),
                ('image', models.ImageField(upload_to='general/')),
            ],
            options={
                'verbose_name': 'Gif Banner',
                'verbose_name_plural': 'Gif Bannerlar',
            },
        ),
        migrations.CreateModel(
            name='Medias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(default='Media', max_length=255)),
                ('title_ru', models.CharField(default='Media', max_length=255)),
                ('title_en', models.CharField(default='Media', max_length=255)),
                ('is_main', models.BooleanField(default=False)),
                ('description_tm', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('video_mobile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('seen', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medialar',
            },
        ),
    ]
