# Generated by Django 3.2 on 2022-08-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_gifbanner_medias'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='content_2_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
