# Generated by Django 3.2 on 2022-08-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_services_content_2_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='medias',
            name='image',
            field=models.ImageField(default='videos/default.jpg', null=True, upload_to='videos/', verbose_name='Surat'),
        ),
        migrations.AddField(
            model_name='medias',
            name='image_mobile',
            field=models.ImageField(default='videos/default.jpg', null=True, upload_to='videos/', verbose_name='Surat Mobile'),
        ),
        migrations.AlterField(
            model_name='medias',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='medias',
            name='video_mobile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Video Mobile'),
        ),
    ]
