# Generated by Django 3.2 on 2022-09-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20220824_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='map_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='stores/', verbose_name='Karta Surat'),
        ),
        migrations.AddField(
            model_name='stores',
            name='map_url',
            field=models.TextField(blank=True, null=True, verbose_name='Karta Link'),
        ),
    ]
