# Generated by Django 3.2 on 2022-09-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20220907_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_main', models.ImageField(blank=True, null=True, upload_to='general/', verbose_name='Esasy Background')),
                ('bg_image1', models.ImageField(upload_to='general/', verbose_name='Bolek Background1')),
                ('bg_image2', models.ImageField(blank=True, null=True, upload_to='general/', verbose_name='Bolek Background2')),
                ('bg_image3', models.ImageField(blank=True, null=True, upload_to='general/', verbose_name='Bolek Background3')),
                ('bg_image4', models.ImageField(blank=True, null=True, upload_to='general/', verbose_name='Bolek Background4')),
                ('bg_image5', models.ImageField(blank=True, null=True, upload_to='general/', verbose_name='Bolek Background5')),
            ],
            options={
                'verbose_name': 'Arka Surat',
                'verbose_name_plural': 'Arka Suratlar',
            },
        ),
    ]
