# Generated by Django 3.2 on 2022-08-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20220725_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(choices=[('Asgabat', 'Asgabat'), ('Ahal', 'Ahal'), ('Balkan', 'Balkan'), ('Dashoguz', 'Dashoguz'), ('Lebap', 'Lebap'), ('Mary', 'Mary')], default='Asgabat', max_length=64, verbose_name='Welaýat'),
        ),
    ]
