# Generated by Django 3.2 on 2022-08-12 04:06

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_profile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profiles.png', upload_to=authentication.models.upload_to, verbose_name='Surat'),
        ),
    ]
