# Generated by Django 3.2 on 2022-09-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
