# Generated by Django 3.2 on 2022-07-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Sargyt', 'verbose_name_plural': 'Sargytlar'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': 'Sargyt Haryt', 'verbose_name_plural': 'Sargyt Harytlary'},
        ),
    ]
