# Generated by Django 3.2 on 2022-08-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20220725_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('TERMINAL', 'TERMINAL'), ('NAGT', 'NAGT')], default='NAGT', max_length=16, verbose_name='Töleg görnüşi'),
        ),
    ]
