# Generated by Django 3.2 on 2022-08-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_payment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sargyt', 'verbose_name_plural': 'Sargytlar'},
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(choices=[('Asgabat', 'Asgabat'), ('Ahal', 'Ahal'), ('Balkan', 'Balkan'), ('Dashoguz', 'Dashoguz'), ('Lebap', 'Lebap'), ('Mary', 'Mary')], default='Asgabat', max_length=64, verbose_name='Welaýat'),
        ),
    ]
